# Local
pathmunge "${HOME}/local/bin"
export LD_LIBRARY_PATH="${HOME}/local/lib64":${LD_LIBRARY_PATH}

# CUDA
pathmunge "/usr/local/cuda/bin"
export LD_LIBRARY_PATH="/usr/local/cuda/lib64":${LD_LIBRARY_PATH}
