# Macports prefix
prefix=/opt/local

# Use GNU Coreutils
pathmunge ${prefix}/libexec/gnubin

# Add executable paths
pathmunge ${prefix}/sbin
pathmunge ${prefix}/bin

# Add MacVim to path
pathmunge /Applications/MacVim.app/Contents/bin

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [[ -f ${prefix}/etc/profile.d/bash_completion.sh ]]; then
    . ${prefix}/etc/profile.d/bash_completion.sh
fi

unset prefix
